#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "UVL-15W controlled Radio Write"

require_file() {
  local path="$1" label="$2"
  if [[ ! -f "$path" ]]; then
    warn "$label was not found: $path"
    exit 1
  fi
}

file_size() {
  if stat -f%z "$1" >/dev/null 2>&1; then
    stat -f%z "$1"
  else
    stat -c%s "$1"
  fi
}

stage "Dedicated Radio and stable connection"
say "Use only the dedicated TYT UVL-15W selected for this controlled test."
step "Confirm the Radio reports firmware 3.07.23. Stop for any other version."
step "Use a charged battery, stable power, and a direct known-good USB cable."
step "Confirm read and write password protection are both disabled."
step "Close every other CPS or serial program that could open the Radio port."
if ! confirm "Are all four conditions true?"; then
  warn "Stopped before opening a serial port."
  exit 1
fi

stage "Prove the official CPS restore path"
say "This must succeed before the browser is allowed to write anything."
step "In the official TYT CPS, perform a complete Radio Read and save its backup."
step "Use that same backup to perform a normal official-CPS write to this Radio."
step "Power-cycle the Radio and perform another complete official-CPS Radio Read."
ask OFFICIAL_BACKUP_PATH "Enter the saved official-CPS backup path:"
require_file "$OFFICIAL_BACKUP_PATH" "Official-CPS backup"
if ! confirm "Did the official write, restart, and follow-up read all succeed?"; then
  warn "Stopped because the proven recovery path is required."
  exit 1
fi

stage "Capture the browser Baseline Backup"
say "Run the normal CPS first, without enabling Radio Write."
step "Start the CPS with: pnpm dev"
step "Open the Radio page in desktop Chrome and perform a complete Radio Read."
step "Download the Raw Backup shown on the Radio page."
ask BASELINE_BACKUP_PATH "Enter the downloaded Raw Backup path:"
require_file "$BASELINE_BACKUP_PATH" "Browser Baseline Backup"
BASELINE_SIZE=$(file_size "$BASELINE_BACKUP_PATH")
if [[ "$BASELINE_SIZE" != "102400" ]]; then
  warn "Baseline Backup is $BASELINE_SIZE bytes; expected exactly 102400."
  exit 1
fi
BASELINE_SHA256=$(shasum -a 256 "$BASELINE_BACKUP_PATH" | awk '{print $1}')
note "Baseline SHA-256: $BASELINE_SHA256"

stage "Open the production release build"
say "Build and start the same release artifact intended for production."
step "Run in a separate terminal:"
say "pnpm build && pnpm start"
step "Open the printed localhost URL in desktop Chrome."
step "Perform a fresh complete Radio Read and confirm firmware 3.07.23."
if ! confirm "Is the fresh Radio Read complete and is Radio Write available?"; then
  warn "Stopped before Radio Write preparation."
  exit 1
fi

stage "Write one reversible change"
say "Use one well-understood display setting only; do not edit signaling, channels, or frequencies."
step "Change exactly one display setting in the Working Codeplug."
step "Select Prepare Radio Write and choose the Source Radio in Chrome's port picker."
step "Review Before and After. There must be exactly one requested change."
step "Stop if Write image preparation lists any additional derived change."
if ! confirm "Does the review contain only the one reversible setting change?"; then
  warn "Stopped before the first write block."
  exit 1
fi
warn "The next UI confirmation can write to the Radio. Do not close Chrome, disconnect USB, or remove power."
if ! confirm "Proceed with Radio Write in the CPS now?"; then
  warn "Stopped before the first write block."
  exit 1
fi
step "In the CPS, select Write to Radio. Wait for Radio Write complete."
pause "Press Enter only after the Radio has rebooted and the CPS reports completion."
if ! confirm "Did the one selected display setting change on the Radio?"; then
  warn "The expected setting is not visible. Stop and retain the operation report."
  exit 1
fi

stage "Restore the original setting"
step "Reverse only the same display setting in the Working Codeplug."
step "Prepare Radio Write, select the Source Radio port, and confirm the review contains only that inverse change."
warn "Stop if any additional or derived change appears."
if ! confirm "Does the review contain only the inverse setting change?"; then
  warn "Stopped before the restore write."
  exit 1
fi
step "Select Write to Radio, wait for completion, and confirm that the original display setting is visible on the Radio."
step "Download the operation report from the Radio Write card and retain it with the original Baseline Backup."
note "The controlled write and inverse write both reached protocol completion."

finish
