const CHANNEL_COUNT = 1_000
const CHANNEL_RECORD_SIZE = 0x30
const CHANNEL_RECORDS_OFFSET = 0x0000
const VALIDITY_BITMAP_OFFSET = 0xd000
const SCAN_BITMAP_OFFSET = 0xd080
const VFO_RECORDS_OFFSET = 0xbb80
const CALL_RECORDS_OFFSET = 0xbbe0
const SPECIAL_CHANNEL_COUNT = 2
const ZONE_MEMBER_LISTS_OFFSET = 0x10000
const SCAN_LIST_MEMBER_LISTS_OFFSET = 0x12000
const CHANNEL_ZONE_MEMBERSHIP_OFFSET = 0x14000
const CHANNEL_SCAN_LIST_MEMBERSHIP_OFFSET = 0x15000
const ZONE_NAMES_OFFSET = 0x16000
const BAND_A_ZONE_SELECTION_OFFSET = 0x16342
const BAND_B_ZONE_SELECTION_OFFSET = 0x16346
const SCAN_LIST_NAMES_OFFSET = 0x16500
const MEMBERSHIP_GROUP_COUNT = 16
const MEMBERSHIP_BITMAP_RECORD_SIZE = 4
const MEMBERSHIP_NAME_SIZE = 0x18
const MEMBER_LIST_SIZE = 0x100
const MEMBER_LIST_SLOT_COUNT = 128

export {
  BAND_A_ZONE_SELECTION_OFFSET,
  BAND_B_ZONE_SELECTION_OFFSET,
  CHANNEL_COUNT,
  CHANNEL_RECORD_SIZE,
  CHANNEL_RECORDS_OFFSET,
  CHANNEL_SCAN_LIST_MEMBERSHIP_OFFSET,
  CHANNEL_ZONE_MEMBERSHIP_OFFSET,
  CALL_RECORDS_OFFSET,
  MEMBER_LIST_SIZE,
  MEMBER_LIST_SLOT_COUNT,
  MEMBERSHIP_BITMAP_RECORD_SIZE,
  MEMBERSHIP_GROUP_COUNT,
  MEMBERSHIP_NAME_SIZE,
  SCAN_BITMAP_OFFSET,
  SCAN_LIST_MEMBER_LISTS_OFFSET,
  SCAN_LIST_NAMES_OFFSET,
  SPECIAL_CHANNEL_COUNT,
  VALIDITY_BITMAP_OFFSET,
  VFO_RECORDS_OFFSET,
  ZONE_MEMBER_LISTS_OFFSET,
  ZONE_NAMES_OFFSET,
}
