const CHANNEL_COUNT = 1_000
const CHANNEL_RECORD_SIZE = 0x30
const CHANNEL_RECORDS_OFFSET = 0x0000
const VALIDITY_BITMAP_OFFSET = 0xd000
const SCAN_BITMAP_OFFSET = 0xd080

export {
  CHANNEL_COUNT,
  CHANNEL_RECORD_SIZE,
  CHANNEL_RECORDS_OFFSET,
  SCAN_BITMAP_OFFSET,
  VALIDITY_BITMAP_OFFSET,
}
