type MenuVisibilityItemDefinition = {
  readonly id: string
  readonly bit: number
  readonly parentId: string | null
}

const MENU_VISIBILITY_ITEMS = [
  { id: "main-menu", bit: 0, parentId: null },
  { id: "channel-settings", bit: 1, parentId: "main-menu" },
  { id: "radio-settings", bit: 2, parentId: "main-menu" },
  { id: "fm-broadcast-receiver", bit: 3, parentId: "main-menu" },
  { id: "aprs", bit: 4, parentId: "main-menu" },
  { id: "gps", bit: 5, parentId: "main-menu" },
  { id: "bluetooth", bit: 6, parentId: "main-menu" },
  { id: "signaling-system", bit: 7, parentId: "main-menu" },
  { id: "channel-information", bit: 8, parentId: "main-menu" },
  { id: "radio-information", bit: 9, parentId: "main-menu" },
  { id: "function-settings", bit: 10, parentId: "radio-settings" },
  { id: "display-settings", bit: 11, parentId: "radio-settings" },
  { id: "audio-settings", bit: 12, parentId: "radio-settings" },
  { id: "key-settings", bit: 13, parentId: "radio-settings" },
  { id: "other-settings", bit: 14, parentId: "radio-settings" },
  { id: "fm-receiver-on-off", bit: 15, parentId: "fm-broadcast-receiver" },
  { id: "fm-receiver-mode", bit: 16, parentId: "fm-broadcast-receiver" },
  { id: "fm-memory-channel-list", bit: 17, parentId: "fm-broadcast-receiver" },
  { id: "gps-on-off", bit: 18, parentId: "gps" },
  { id: "gps-constellation-mode", bit: 19, parentId: "gps" },
  { id: "time-zone", bit: 20, parentId: "gps" },
  { id: "gps-position-information", bit: 21, parentId: "gps" },
  { id: "gps-satellite-information", bit: 22, parentId: "gps" },
  { id: "bluetooth-on-off", bit: 23, parentId: "bluetooth" },
  { id: "bluetooth-mode", bit: 24, parentId: "bluetooth" },
  { id: "bluetooth-headset-pairing", bit: 25, parentId: "bluetooth" },
  { id: "bluetooth-ptt-pairing", bit: 26, parentId: "bluetooth" },
  { id: "built-in-speaker-control", bit: 27, parentId: "bluetooth" },
  { id: "built-in-microphone-control", bit: 28, parentId: "bluetooth" },
  { id: "bluetooth-speaker-gain", bit: 29, parentId: "bluetooth" },
  { id: "bluetooth-microphone-gain", bit: 30, parentId: "bluetooth" },
  { id: "bluetooth-device-table", bit: 31, parentId: "bluetooth" },
  { id: "bluetooth-status-information", bit: 32, parentId: "bluetooth" },
  { id: "dtmf", bit: 33, parentId: "signaling-system" },
  { id: "two-tone", bit: 34, parentId: "signaling-system" },
  { id: "five-tone", bit: 35, parentId: "signaling-system" },
  { id: "dtmf-local-id", bit: 36, parentId: "dtmf" },
  { id: "dtmf-separator", bit: 37, parentId: "dtmf" },
  { id: "dtmf-group-call-code", bit: 38, parentId: "dtmf" },
  { id: "dtmf-dialer-type", bit: 39, parentId: "dtmf" },
  { id: "dtmf-encoder-settings", bit: 40, parentId: "dtmf" },
  { id: "dtmf-decoder-settings", bit: 41, parentId: "dtmf" },
  { id: "dtmf-ptt-id-list", bit: 42, parentId: "dtmf" },
  { id: "dtmf-code-table", bit: 43, parentId: "dtmf" },
  { id: "two-tone-encoder-decoder-settings", bit: 44, parentId: "two-tone" },
  { id: "two-tone-code-table", bit: 45, parentId: "two-tone" },
  { id: "two-tone-decode-list", bit: 46, parentId: "two-tone" },
  { id: "five-tone-local-id", bit: 47, parentId: "five-tone" },
  { id: "five-tone-encoder-settings", bit: 48, parentId: "five-tone" },
  { id: "five-tone-decoder-settings", bit: 49, parentId: "five-tone" },
  { id: "five-tone-ptt-id-list", bit: 50, parentId: "five-tone" },
  { id: "five-tone-code-table", bit: 51, parentId: "five-tone" },
  { id: "five-tone-information-code-table", bit: 52, parentId: "five-tone" },
  { id: "channel-info-rx-frequency", bit: 53, parentId: "channel-information" },
  { id: "channel-info-tx-frequency", bit: 54, parentId: "channel-information" },
  { id: "channel-info-tx-power", bit: 55, parentId: "channel-information" },
  { id: "channel-info-channel-mode", bit: 56, parentId: "channel-information" },
  { id: "channel-info-channel-name", bit: 57, parentId: "channel-information" },
  {
    id: "channel-info-offset-duplex-mode",
    bit: 58,
    parentId: "channel-information",
  },
  {
    id: "channel-info-duplex-offset-frequency",
    bit: 59,
    parentId: "channel-information",
  },
  {
    id: "channel-info-talk-around-reverse",
    bit: 60,
    parentId: "channel-information",
  },
  {
    id: "channel-info-frequency-step",
    bit: 61,
    parentId: "channel-information",
  },
  { id: "channel-info-rx-only", bit: 62, parentId: "channel-information" },
  {
    id: "channel-info-busy-channel-lockout",
    bit: 63,
    parentId: "channel-information",
  },
  { id: "channel-info-scan-flag", bit: 64, parentId: "channel-information" },
  { id: "channel-info-ptt-id", bit: 65, parentId: "channel-information" },
  { id: "channel-info-scrambler", bit: 66, parentId: "channel-information" },
  { id: "channel-info-squelch-type", bit: 67, parentId: "channel-information" },
  { id: "channel-info-tone-encode", bit: 68, parentId: "channel-information" },
  { id: "channel-info-tone-decode", bit: 69, parentId: "channel-information" },
  { id: "channel-info-dcs-polarity", bit: 70, parentId: "channel-information" },
  {
    id: "channel-info-optional-signaling",
    bit: 71,
    parentId: "channel-information",
  },
  { id: "channel-info-aprs-receive", bit: 72, parentId: "channel-information" },
  { id: "radio-info-model", bit: 73, parentId: "radio-information" },
  { id: "radio-info-battery-voltage", bit: 74, parentId: "radio-information" },
  { id: "radio-info-radio-identifier", bit: 75, parentId: "radio-information" },
  { id: "radio-info-hardware-version", bit: 76, parentId: "radio-information" },
  { id: "radio-info-firmware-version", bit: 77, parentId: "radio-information" },
  {
    id: "radio-info-firmware-build-date",
    bit: 78,
    parentId: "radio-information",
  },
  {
    id: "radio-info-firmware-build-time",
    bit: 79,
    parentId: "radio-information",
  },
  { id: "channel-operations", bit: 80, parentId: "channel-settings" },
  { id: "channel-rx-tx-frequencies", bit: 81, parentId: "channel-settings" },
  { id: "channel-tx-power", bit: 82, parentId: "channel-settings" },
  { id: "channel-mode", bit: 83, parentId: "channel-settings" },
  { id: "channel-name", bit: 84, parentId: "channel-settings" },
  { id: "channel-talk-around-reverse", bit: 85, parentId: "channel-settings" },
  { id: "channel-frequency-step", bit: 86, parentId: "channel-settings" },
  { id: "channel-rx-only", bit: 87, parentId: "channel-settings" },
  { id: "channel-busy-channel-lockout", bit: 88, parentId: "channel-settings" },
  { id: "channel-scan-flag", bit: 89, parentId: "channel-settings" },
  { id: "channel-scrambler", bit: 90, parentId: "channel-settings" },
  { id: "channel-squelch-control", bit: 91, parentId: "channel-settings" },
  { id: "channel-aprs-receive", bit: 92, parentId: "channel-settings" },
  { id: "channel-zones", bit: 93, parentId: "channel-settings" },
  { id: "channel-scan-lists", bit: 94, parentId: "channel-settings" },
  { id: "aprs-local-callsign", bit: 95, parentId: "aprs" },
  { id: "aprs-local-ssid", bit: 96, parentId: "aprs" },
  { id: "aprs-local-symbol", bit: 97, parentId: "aprs" },
  { id: "aprs-transmit-settings", bit: 98, parentId: "aprs" },
  { id: "aprs-decode-settings", bit: 99, parentId: "aprs" },
  { id: "aprs-station-list", bit: 100, parentId: "aprs" },
  { id: "aprs-tnc", bit: 101, parentId: "aprs" },
  { id: "function-rx-tx-mode", bit: 102, parentId: "function-settings" },
  {
    id: "function-cross-band-repeater-mode",
    bit: 103,
    parentId: "function-settings",
  },
  {
    id: "function-cross-band-repeater-monitoring",
    bit: 104,
    parentId: "function-settings",
  },
  { id: "function-squelch-level", bit: 105, parentId: "function-settings" },
  { id: "function-transmit-timeout", bit: 106, parentId: "function-settings" },
  {
    id: "function-transmit-channel-selection",
    bit: 107,
    parentId: "function-settings",
  },
  { id: "function-call-hold-time", bit: 108, parentId: "function-settings" },
  {
    id: "function-band-a-operating-mode",
    bit: 109,
    parentId: "function-settings",
  },
  {
    id: "function-band-b-operating-mode",
    bit: 110,
    parentId: "function-settings",
  },
  {
    id: "function-squelch-tail-elimination",
    bit: 111,
    parentId: "function-settings",
  },
  {
    id: "function-single-tone-transmit",
    bit: 112,
    parentId: "function-settings",
  },
  { id: "function-scanning", bit: 113, parentId: "function-settings" },
  { id: "function-power-save", bit: 114, parentId: "function-settings" },
  { id: "function-weather-channels", bit: 115, parentId: "function-settings" },
  { id: "function-zones", bit: 116, parentId: "function-settings" },
  { id: "display-lcd-backlight", bit: 117, parentId: "display-settings" },
  { id: "display-power-on", bit: 118, parentId: "display-settings" },
  { id: "display-system-language", bit: 119, parentId: "display-settings" },
  { id: "display-menu-auto-exit", bit: 120, parentId: "display-settings" },
  {
    id: "display-memory-channels-shown",
    bit: 121,
    parentId: "display-settings",
  },
  { id: "display-battery-style", bit: 122, parentId: "display-settings" },
  { id: "display-rx-indicator-led", bit: 123, parentId: "display-settings" },
  {
    id: "display-screen-off-indicator-led",
    bit: 124,
    parentId: "display-settings",
  },
  {
    id: "display-received-signal-strength",
    bit: 125,
    parentId: "display-settings",
  },
  { id: "display-units", bit: 126, parentId: "display-settings" },
  { id: "audio-alert-tones", bit: 127, parentId: "audio-settings" },
  { id: "audio-ai-noise-reduction", bit: 128, parentId: "audio-settings" },
  { id: "audio-ai-vox", bit: 129, parentId: "audio-settings" },
  { id: "audio-microphone-gain", bit: 130, parentId: "audio-settings" },
  { id: "key-lock", bit: 131, parentId: "key-settings" },
  { id: "programmable-keys", bit: 132, parentId: "key-settings" },
  { id: "other-initialize-settings", bit: 133, parentId: "other-settings" },
  { id: "other-initialize-vfo-channels", bit: 134, parentId: "other-settings" },
  { id: "other-initialize-mr-channels", bit: 135, parentId: "other-settings" },
  { id: "other-initialize-zones", bit: 136, parentId: "other-settings" },
  { id: "other-initialize-scan-lists", bit: 137, parentId: "other-settings" },
  { id: "other-factory-reset", bit: 138, parentId: "other-settings" },
  { id: "key-auto-lock", bit: 139, parentId: "key-lock" },
  { id: "key-lock-type", bit: 140, parentId: "key-lock" },
  { id: "key-lock-delay", bit: 141, parentId: "key-lock" },
  { id: "key-side-1-short", bit: 142, parentId: "programmable-keys" },
  { id: "key-side-1-long", bit: 143, parentId: "programmable-keys" },
  { id: "key-side-2-short", bit: 144, parentId: "programmable-keys" },
  { id: "key-side-2-long", bit: 145, parentId: "programmable-keys" },
  { id: "key-top-short", bit: 146, parentId: "programmable-keys" },
  { id: "key-top-long", bit: 147, parentId: "programmable-keys" },
  { id: "key-menu-long", bit: 148, parentId: "programmable-keys" },
  { id: "key-back-long", bit: 149, parentId: "programmable-keys" },
  { id: "key-digit-0-long", bit: 150, parentId: "programmable-keys" },
  { id: "key-digit-1-long", bit: 151, parentId: "programmable-keys" },
  { id: "key-digit-2-long", bit: 152, parentId: "programmable-keys" },
  { id: "key-digit-3-long", bit: 153, parentId: "programmable-keys" },
  { id: "key-digit-4-long", bit: 154, parentId: "programmable-keys" },
  { id: "key-digit-5-long", bit: 155, parentId: "programmable-keys" },
  { id: "key-digit-6-long", bit: 156, parentId: "programmable-keys" },
  { id: "key-digit-7-long", bit: 157, parentId: "programmable-keys" },
  { id: "key-digit-8-long", bit: 158, parentId: "programmable-keys" },
  { id: "key-digit-9-long", bit: 159, parentId: "programmable-keys" },
  {
    id: "display-backlight-level",
    bit: 160,
    parentId: "display-lcd-backlight",
  },
  { id: "display-auto-dimming", bit: 161, parentId: "display-lcd-backlight" },
  { id: "display-auto-dim-delay", bit: 162, parentId: "display-lcd-backlight" },
  {
    id: "display-exit-dimming-rx",
    bit: 163,
    parentId: "display-lcd-backlight",
  },
  {
    id: "display-exit-dimming-tx",
    bit: 164,
    parentId: "display-lcd-backlight",
  },
  { id: "display-theme", bit: 165, parentId: "display-settings" },
  { id: "radio-info-image-version", bit: 166, parentId: "radio-information" },
  {
    id: "radio-info-language-version",
    bit: 167,
    parentId: "radio-information",
  },
  { id: "audio-am-rx-gain", bit: 168, parentId: "audio-settings" },
  { id: "audio-am-n-rx-gain", bit: 169, parentId: "audio-settings" },
  { id: "function-auto-repeater", bit: 170, parentId: "function-settings" },
  { id: "function-ci-t", bit: 171, parentId: "function-settings" },
  { id: "function-auto-am-mode", bit: 172, parentId: "function-settings" },
  { id: "function-scan-edge-init", bit: 173, parentId: "function-settings" },
] as const satisfies readonly MenuVisibilityItemDefinition[]

type MenuVisibilityItem = (typeof MENU_VISIBILITY_ITEMS)[number]
type MenuVisibilityItemId = MenuVisibilityItem["id"]

export { MENU_VISIBILITY_ITEMS }
export type { MenuVisibilityItem, MenuVisibilityItemId }
